language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install coveralls
  - python setup.py install
script:
  - coverage run setup.py test
  - coverage report --fail-under=90
after_success:
  - coveralls
